# Generated by Django 2.0.5 on 2018-09-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
