# Generated by Django 2.0.5 on 2018-09-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedImage', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='document',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploadedFile',
            field=models.FileField(default='file_folder/None/no-file.txt', upload_to='file_folder/'),
        ),
    ]
