# Generated by Django 2.0.5 on 2018-09-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20180906_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadedFile',
            field=models.FileField(upload_to='file_folder'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='uploadedImage',
            field=models.ImageField(upload_to='pic_folder'),
        ),
    ]
