# Generated by Django 2.0.5 on 2018-09-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20180906_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='uploadedFile',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='uploadedImage',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='documentfile',
            field=models.FileField(blank=True, upload_to='document_folder'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='2018-09-6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='imagefile',
            field=models.ImageField(blank=True, upload_to='image_folder'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='2018-09-6'),
            preserve_default=False,
        ),
    ]
