# Generated by Django 2.0.5 on 2018-09-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20180906_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='documentfile',
            field=models.FileField(blank=True, default='default.txt', upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='imagefile',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
