# Generated by Django 2.0.5 on 2018-09-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('courseDetail', models.CharField(max_length=500)),
                ('dateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
