# Generated by Django 2.0.5 on 2018-08-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('dateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseDescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDesc'),
        ),
    ]
