# Generated by Django 2.0.7 on 2018-07-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20180724_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jointrip', to='belt_app.Trip'),
        ),
        migrations.AlterField(
            model_name='jointrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jointrip', to='belt_app.User'),
        ),
    ]
