# Generated by Django 2.0.5 on 2018-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='documentfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/$D/'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='imagefile',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
