# Generated by Django 2.0.5 on 2018-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_apps', '0002_auto_20180913_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='imagefile',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/$D/'),
        ),
    ]
