# Generated by Django 2.1.1 on 2018-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_apps', '0007_auto_20180913_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplefiles', models.FileField(blank=True, null=True, upload_to='documents/%m-%d-%y/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
