# Generated by Django 2.0.5 on 2018-07-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180726_0715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
